# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: "丁国盛课题组"
 params:
   description: Site description in Chinese...
 menu:
   main:

     - name: "成果"
       url: publication
       weight: 10
     - name: "成员"
       url: people
       weight: 30
     - name: "联系我们"
       url: contact
       weight: 40
     - name: "Wiki"
       url: wiki
       weight: 50 
# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  menu:
   main:
     - name: "Publications"
       url: publication
       weight: 10
     - name: "People"
       url: people
       weight: 30
     - name: "Contact"
       url: contact
       weight: 40
     - name: "Wiki"
       url: wiki
       weight: 50 


